name: CI/CD flask Docker

on:
  push:
    branches: 
        - main

jobs:
  ci:
    name: Build and Test  
    runs-on: self-hosted  # ← CHANGÉ : utilise votre machine Windows
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
            pip install -r requirements.txt

  cd:
    name: Docker Build & Deploy on Windows
    runs-on: self-hosted  # ← CHANGÉ : utilise votre machine Windows
    needs: ci
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: Docker Build
        run: |
          docker build -t flask_devops_demo:latest .
          
      - name: Stop and remove old container
        run: |
          docker stop flask_app 2>$null
          docker rm flask_app 2>$null
          
      - name: Run new container
        run: |
          docker run -d -p 5000:5000 --name flask_app flask_devops_demo:latest
          
      - name: Verify deployment
        run: |
          Write-Host "Application déployée sur http://localhost:5000"
          Write-Host "IP de la machine :"
          Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -notlike "*Loopback*"} | Select-Object -ExpandProperty IPAddress